/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as SampleRouteImport } from './routes/sample'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppFixesRouteImport } from './routes/app/fixes'
import { Route as AppNewRouteImport } from './routes/app/new'
import { Route as AppPoliciesRouteImport } from './routes/app/policies'
import { Route as AppRunsRouteImport } from './routes/app/runs'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppUsageRouteImport } from './routes/app/usage'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app/projects.$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app/projects.$projectId.index'
import { Route as AppProjectsProjectIdArchitectureRouteImport } from './routes/app/projects.$projectId.architecture'
import { Route as AppProjectsProjectIdFixesRouteImport } from './routes/app/projects.$projectId.fixes'
import { Route as AppProjectsProjectIdIssuesRouteImport } from './routes/app/projects.$projectId.issues'
import { Route as AppProjectsProjectIdRunsRouteImport } from './routes/app/projects.$projectId.runs'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/app/projects.$projectId.settings'
import { Route as AppProjectsProjectIdIssuesIndexRouteImport } from './routes/app/projects.$projectId.issues.index'
import { Route as AppProjectsProjectIdIssuesFindingIdRouteImport } from './routes/app/projects.$projectId.issues.$findingId'
import { Route as AppProjectsProjectIdRunsIndexRouteImport } from './routes/app/projects.$projectId.runs.index'
import { Route as AppProjectsProjectIdRunsRunIdRouteImport } from './routes/app/projects.$projectId.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleRoute = SampleRouteImport.update({
  id: '/sample',
  path: '/sample',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFixesRoute = AppFixesRouteImport.update({
  id: '/fixes',
  path: '/fixes',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRoute = AppPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdArchitectureRoute =
  AppProjectsProjectIdArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdFixesRoute =
  AppProjectsProjectIdFixesRouteImport.update({
    id: '/fixes',
    path: '/fixes',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdIssuesRoute =
  AppProjectsProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdRunsRoute =
  AppProjectsProjectIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdIssuesIndexRoute =
  AppProjectsProjectIdIssuesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdIssuesRoute,
  } as any)
const AppProjectsProjectIdIssuesFindingIdRoute =
  AppProjectsProjectIdIssuesFindingIdRouteImport.update({
    id: '/$findingId',
    path: '/$findingId',
    getParentRoute: () => AppProjectsProjectIdIssuesRoute,
  } as any)
const AppProjectsProjectIdRunsIndexRoute =
  AppProjectsProjectIdRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRunsRoute,
  } as any)
const AppProjectsProjectIdRunsRunIdRoute =
  AppProjectsProjectIdRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AppProjectsProjectIdRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checklist': typeof ChecklistRoute
  '/sample': typeof SampleRoute
  '/app/fixes': typeof AppFixesRoute
  '/app/new': typeof AppNewRoute
  '/app/policies': typeof AppPoliciesRoute
  '/app/runs': typeof AppRunsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/projects/$projectId/architecture': typeof AppProjectsProjectIdArchitectureRoute
  '/app/projects/$projectId/fixes': typeof AppProjectsProjectIdFixesRoute
  '/app/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRouteWithChildren
  '/app/projects/$projectId/runs': typeof AppProjectsProjectIdRunsRouteWithChildren
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/issues/$findingId': typeof AppProjectsProjectIdIssuesFindingIdRoute
  '/app/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/app/projects/$projectId/issues/': typeof AppProjectsProjectIdIssuesIndexRoute
  '/app/projects/$projectId/runs/': typeof AppProjectsProjectIdRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/sample': typeof SampleRoute
  '/app/fixes': typeof AppFixesRoute
  '/app/new': typeof AppNewRoute
  '/app/policies': typeof AppPoliciesRoute
  '/app/runs': typeof AppRunsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$projectId/architecture': typeof AppProjectsProjectIdArchitectureRoute
  '/app/projects/$projectId/fixes': typeof AppProjectsProjectIdFixesRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/issues/$findingId': typeof AppProjectsProjectIdIssuesFindingIdRoute
  '/app/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/app/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesIndexRoute
  '/app/projects/$projectId/runs': typeof AppProjectsProjectIdRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checklist': typeof ChecklistRoute
  '/sample': typeof SampleRoute
  '/app/fixes': typeof AppFixesRoute
  '/app/new': typeof AppNewRoute
  '/app/policies': typeof AppPoliciesRoute
  '/app/runs': typeof AppRunsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/app/projects/$projectId/architecture': typeof AppProjectsProjectIdArchitectureRoute
  '/app/projects/$projectId/fixes': typeof AppProjectsProjectIdFixesRoute
  '/app/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRouteWithChildren
  '/app/projects/$projectId/runs': typeof AppProjectsProjectIdRunsRouteWithChildren
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/app/projects/$projectId/issues/$findingId': typeof AppProjectsProjectIdIssuesFindingIdRoute
  '/app/projects/$projectId/runs/$runId': typeof AppProjectsProjectIdRunsRunIdRoute
  '/app/projects/$projectId/issues/': typeof AppProjectsProjectIdIssuesIndexRoute
  '/app/projects/$projectId/runs/': typeof AppProjectsProjectIdRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/checklist'
    | '/sample'
    | '/app/fixes'
    | '/app/new'
    | '/app/policies'
    | '/app/runs'
    | '/app/settings'
    | '/app/usage'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/architecture'
    | '/app/projects/$projectId/fixes'
    | '/app/projects/$projectId/issues'
    | '/app/projects/$projectId/runs'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/issues/$findingId'
    | '/app/projects/$projectId/runs/$runId'
    | '/app/projects/$projectId/issues/'
    | '/app/projects/$projectId/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklist'
    | '/sample'
    | '/app/fixes'
    | '/app/new'
    | '/app/policies'
    | '/app/runs'
    | '/app/settings'
    | '/app/usage'
    | '/app'
    | '/app/projects/$projectId/architecture'
    | '/app/projects/$projectId/fixes'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/issues/$findingId'
    | '/app/projects/$projectId/runs/$runId'
    | '/app/projects/$projectId/issues'
    | '/app/projects/$projectId/runs'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/checklist'
    | '/sample'
    | '/app/fixes'
    | '/app/new'
    | '/app/policies'
    | '/app/runs'
    | '/app/settings'
    | '/app/usage'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/$projectId/architecture'
    | '/app/projects/$projectId/fixes'
    | '/app/projects/$projectId/issues'
    | '/app/projects/$projectId/runs'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId/'
    | '/app/projects/$projectId/issues/$findingId'
    | '/app/projects/$projectId/runs/$runId'
    | '/app/projects/$projectId/issues/'
    | '/app/projects/$projectId/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChecklistRoute: typeof ChecklistRoute
  SampleRoute: typeof SampleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample': {
      id: '/sample'
      path: '/sample'
      fullPath: '/sample'
      preLoaderRoute: typeof SampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fixes': {
      id: '/app/fixes'
      path: '/fixes'
      fullPath: '/app/fixes'
      preLoaderRoute: typeof AppFixesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/policies': {
      id: '/app/policies'
      path: '/policies'
      fullPath: '/app/policies'
      preLoaderRoute: typeof AppPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs': {
      id: '/app/runs'
      path: '/runs'
      fullPath: '/app/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/architecture': {
      id: '/app/projects/$projectId/architecture'
      path: '/architecture'
      fullPath: '/app/projects/$projectId/architecture'
      preLoaderRoute: typeof AppProjectsProjectIdArchitectureRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/fixes': {
      id: '/app/projects/$projectId/fixes'
      path: '/fixes'
      fullPath: '/app/projects/$projectId/fixes'
      preLoaderRoute: typeof AppProjectsProjectIdFixesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/issues': {
      id: '/app/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/app/projects/$projectId/issues'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/runs': {
      id: '/app/projects/$projectId/runs'
      path: '/runs'
      fullPath: '/app/projects/$projectId/runs'
      preLoaderRoute: typeof AppProjectsProjectIdRunsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/settings': {
      id: '/app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/app/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/app/projects/$projectId/issues/': {
      id: '/app/projects/$projectId/issues/'
      path: '/'
      fullPath: '/app/projects/$projectId/issues/'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdIssuesRoute
    }
    '/app/projects/$projectId/issues/$findingId': {
      id: '/app/projects/$projectId/issues/$findingId'
      path: '/$findingId'
      fullPath: '/app/projects/$projectId/issues/$findingId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesFindingIdRouteImport
      parentRoute: typeof AppProjectsProjectIdIssuesRoute
    }
    '/app/projects/$projectId/runs/': {
      id: '/app/projects/$projectId/runs/'
      path: '/'
      fullPath: '/app/projects/$projectId/runs/'
      preLoaderRoute: typeof AppProjectsProjectIdRunsIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRunsRoute
    }
    '/app/projects/$projectId/runs/$runId': {
      id: '/app/projects/$projectId/runs/$runId'
      path: '/$runId'
      fullPath: '/app/projects/$projectId/runs/$runId'
      preLoaderRoute: typeof AppProjectsProjectIdRunsRunIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRunsRoute
    }
  }
}

interface AppProjectsProjectIdIssuesRouteChildren {
  AppProjectsProjectIdIssuesFindingIdRoute: typeof AppProjectsProjectIdIssuesFindingIdRoute
  AppProjectsProjectIdIssuesIndexRoute: typeof AppProjectsProjectIdIssuesIndexRoute
}

const AppProjectsProjectIdIssuesRouteChildren: AppProjectsProjectIdIssuesRouteChildren =
  {
    AppProjectsProjectIdIssuesFindingIdRoute:
      AppProjectsProjectIdIssuesFindingIdRoute,
    AppProjectsProjectIdIssuesIndexRoute: AppProjectsProjectIdIssuesIndexRoute,
  }

const AppProjectsProjectIdIssuesRouteWithChildren =
  AppProjectsProjectIdIssuesRoute._addFileChildren(
    AppProjectsProjectIdIssuesRouteChildren,
  )

interface AppProjectsProjectIdRunsRouteChildren {
  AppProjectsProjectIdRunsRunIdRoute: typeof AppProjectsProjectIdRunsRunIdRoute
  AppProjectsProjectIdRunsIndexRoute: typeof AppProjectsProjectIdRunsIndexRoute
}

const AppProjectsProjectIdRunsRouteChildren: AppProjectsProjectIdRunsRouteChildren =
  {
    AppProjectsProjectIdRunsRunIdRoute: AppProjectsProjectIdRunsRunIdRoute,
    AppProjectsProjectIdRunsIndexRoute: AppProjectsProjectIdRunsIndexRoute,
  }

const AppProjectsProjectIdRunsRouteWithChildren =
  AppProjectsProjectIdRunsRoute._addFileChildren(
    AppProjectsProjectIdRunsRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdArchitectureRoute: typeof AppProjectsProjectIdArchitectureRoute
  AppProjectsProjectIdFixesRoute: typeof AppProjectsProjectIdFixesRoute
  AppProjectsProjectIdIssuesRoute: typeof AppProjectsProjectIdIssuesRouteWithChildren
  AppProjectsProjectIdRunsRoute: typeof AppProjectsProjectIdRunsRouteWithChildren
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdArchitectureRoute: AppProjectsProjectIdArchitectureRoute,
  AppProjectsProjectIdFixesRoute: AppProjectsProjectIdFixesRoute,
  AppProjectsProjectIdIssuesRoute: AppProjectsProjectIdIssuesRouteWithChildren,
  AppProjectsProjectIdRunsRoute: AppProjectsProjectIdRunsRouteWithChildren,
  AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppFixesRoute: typeof AppFixesRoute
  AppNewRoute: typeof AppNewRoute
  AppPoliciesRoute: typeof AppPoliciesRoute
  AppRunsRoute: typeof AppRunsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppFixesRoute: AppFixesRoute,
  AppNewRoute: AppNewRoute,
  AppPoliciesRoute: AppPoliciesRoute,
  AppRunsRoute: AppRunsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChecklistRoute: ChecklistRoute,
  SampleRoute: SampleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
